"""Add decision_status to candidates

Revision ID: 19677fd90a5e
Revises: 6b27e62cae20
Create Date: 2026-01-02 20:47:48.902427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19677fd90a5e'
down_revision = '6b27e62cae20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('experience_years')
        batch_op.drop_column('decision_status')

    # ### end Alembic commands ###
