"""add review_emails table

Revision ID: 4663faf57a81
Revises: e32b07a7b0b4
Create Date: 2026-02-25 14:17:51.160610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4663faf57a81'
down_revision = 'e32b07a7b0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('stage_notes_snapshot', sa.Text(), nullable=True),
    sa.Column('analysis_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_subject', sa.String(length=256), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('google_form_configs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_form_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('form_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('form_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('google_form_configs_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('google_form_configs_pkey'))
    )
    op.drop_table('review_emails')
    # ### end Alembic commands ###
