"""Add job management fields

Revision ID: 67e7b2e359e6
Revises: 19677fd90a5e
Create Date: 2026-01-02 21:08:22.016564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e7b2e359e6'
down_revision = '19677fd90a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('experience_range', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('experience_range')
        batch_op.drop_column('department')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
