"""Add review_status to candidates

Revision ID: 6b27e62cae20
Revises: 98c464010b5b
Create Date: 2026-01-02 20:26:19.146182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b27e62cae20'
down_revision = '98c464010b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
