"""add_async_status

Revision ID: 98c464010b5b
Revises: 272d4acdf55e
Create Date: 2026-01-01 23:36:33.693990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c464010b5b'
down_revision = '272d4acdf55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('processing_status')

    # ### end Alembic commands ###
