"""Add candidate details

Revision ID: e32b07a7b0b4
Revises: 6a401f89b163
Create Date: 2026-01-09 00:04:38.726835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e32b07a7b0b4'
down_revision = '6a401f89b163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('extracted_data')
        batch_op.drop_column('certificates')
        batch_op.drop_column('projects')
        batch_op.drop_column('work_experience')
        batch_op.drop_column('education')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
